version: '3'

networks:
  cluster_net:

services:

  neo4j:
    hostname: neo4j
    image: neo4j:4.0-enterprise
    networks:
      - cluster_net
    ports:
      - 7474:7474
      - 6477:6477
      - 7687:7687
    volumes:
      - $HOME/tmp/docker/fabric-dev/neo4j/conf:/conf
      - $HOME/tmp/docker/fabric-dev/neo4j/data:/data
      - $HOME/tmp/docker/fabric-dev/neo4j/logs:/logs
      - $HOME/tmp/docker/fabric-dev/neo4j/metrics:/metrics
      - $HOME/tmp/docker/fabric-dev/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_fabric_database_name=example
      - NEO4J_fabric_graph_0_uri=neo4j://neo4j:7687
      - NEO4J_fabric_graph_0_database=db1
      - NEO4J_fabric_graph_1_uri=neo4j://neo4j:7687
      - NEO4J_fabric_graph_1_database=db2
