# https://neo4j.com/docs/operations-manual/current/fabric/configuration/#_cluster_setup_with_no_single_point_of_failure_example
version: '3'

networks:
  cluster_net:

services:

  core1:
    hostname: core1
    image: neo4j:4.0-enterprise
    networks:
      - cluster_net
    ports:
      - 17687:17687
    volumes:
      - $HOME/tmp/docker/fabric-cluster/neo4j-core1/conf:/conf
      - $HOME/tmp/docker/fabric-cluster/neo4j-core1/data:/data
      - $HOME/tmp/docker/fabric-cluster/neo4j-core1/logs:/logs
      - $HOME/tmp/docker/fabric-cluster/neo4j-core1/metrics:/metrics
      - $HOME/tmp/docker/fabric-cluster/neo4j-core1/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_dbms_mode=CORE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3
      - NEO4J_causal__clustering_initial__discovery__members=core1:5000,core2:5000,core3:5000
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6473
      - NEO4J_dbms_connector_bolt_listen__address=:17687
      - NEO4J_dbms_connector_bolt_advertised__address=core1:17687
      - NEO4J_dbms_default__database=db1
      - NEO4JLABS_PLUGINS=["apoc"]

  core2:
    hostname: core2
    image: neo4j:4.0-enterprise
    networks:
      - cluster_net
    ports:
      - 27687:27687
    volumes:
      - $HOME/tmp/docker/fabric-cluster/neo4j-core2/conf:/conf
      - $HOME/tmp/docker/fabric-cluster/neo4j-core2/data:/data
      - $HOME/tmp/docker/fabric-cluster/neo4j-core2/logs:/logs
      - $HOME/tmp/docker/fabric-cluster/neo4j-core2/metrics:/metrics
      - $HOME/tmp/docker/fabric-cluster/neo4j-core2/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_dbms_mode=CORE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3
      - NEO4J_causal__clustering_initial__discovery__members=core1:5000,core2:5000,core3:5000
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6473
      - NEO4J_dbms_connector_bolt_listen__address=:27687
      - NEO4J_dbms_connector_bolt_advertised__address=core2:27687
      - NEO4J_dbms_default__database=db1
      - NEO4JLABS_PLUGINS=["apoc"]

  core3:
    hostname: core3
    image: neo4j:4.0-enterprise
    networks:
      - cluster_net
    ports:
      - 37687:37687
    volumes:
      - $HOME/tmp/docker/fabric-cluster/neo4j-core3/conf:/conf
      - $HOME/tmp/docker/fabric-cluster/neo4j-core3/data:/data
      - $HOME/tmp/docker/fabric-cluster/neo4j-core3/logs:/logs
      - $HOME/tmp/docker/fabric-cluster/neo4j-core3/metrics:/metrics
      - $HOME/tmp/docker/fabric-cluster/neo4j-core3/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_dbms_mode=CORE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3
      - NEO4J_causal__clustering_initial__discovery__members=core1:5000,core2:5000,core3:5000
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6473
      - NEO4J_dbms_connector_bolt_listen__address=:37687
      - NEO4J_dbms_connector_bolt_advertised__address=core3:37687
      - NEO4J_dbms_default__database=db1
      - NEO4JLABS_PLUGINS=["apoc"]

  server1:
    hostname: server1
    image: neo4j:4.0-enterprise
    networks:
      - cluster_net
    links:
      - core1
      - core2
      - core3
    ports:
      - 47474:7474
      - 46473:6473
      - 47687:7687
    volumes:
      - $HOME/tmp/docker/fabric-cluster/neo4j-server1/conf:/conf
      - $HOME/tmp/docker/fabric-cluster/neo4j-server1/data:/data
      - $HOME/tmp/docker/fabric-cluster/neo4j-server1/logs:/logs
      - $HOME/tmp/docker/fabric-cluster/neo4j-server1/metrics:/metrics
      - $HOME/tmp/docker/fabric-cluster/neo4j-server1/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_dbms_mode=SINGLE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6473
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_fabric_database_name=example
      - NEO4J_fabric_routing_servers=server1:47687,server2:57687
      - NEO4J_fabric_graph_0_name=graphA
      - NEO4J_fabric_graph_0_uri=neo4j://core1:17687,neo4j://core2:27687,neo4j://core3:37687
      - NEO4J_fabric_graph_0_database=db1
      - NEO4J_fabric_graph_1_name=graphB
      - NEO4J_fabric_graph_1_uri=neo4j://core1:17687,neo4j://core2:27687,neo4j://core3:37687
      - NEO4J_fabric_graph_1_database=db2
      - NEO4J_fabric_graph_2_name=graphC
      - NEO4J_fabric_graph_2_uri=neo4j://core1:17687,neo4j://core2:27687,neo4j://core3:37687
      - NEO4J_fabric_graph_2_database=db3
      - NEO4J_dbms_connector_bolt_advertised__address=server1:47687
      - NEO4JLABS_PLUGINS=["apoc"]

  server2:
    hostname: server2
    image: neo4j:4.0-enterprise
    networks:
      - cluster_net
    links:
      - core1
      - core2
      - core3
    ports:
      - 57474:7474
      - 56473:6473
      - 57687:7687
    volumes:
      - $HOME/tmp/docker/fabric-cluster/neo4j-server2/conf:/conf
      - $HOME/tmp/docker/fabric-cluster/neo4j-server2/data:/data
      - $HOME/tmp/docker/fabric-cluster/neo4j-server2/logs:/logs
      - $HOME/tmp/docker/fabric-cluster/neo4j-server2/metrics:/metrics
      - $HOME/tmp/docker/fabric-cluster/neo4j-server2/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_dbms_mode=SINGLE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6473
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_fabric_database_name=example
      - NEO4J_fabric_routing_servers=server1:47687,server2:57687
      - NEO4J_fabric_graph_0_name=graphA
      - NEO4J_fabric_graph_0_uri=neo4j://core1:17687,neo4j://core2:27687,neo4j://core3:37687
      - NEO4J_fabric_graph_0_database=db1
      - NEO4J_fabric_graph_1_name=graphB
      - NEO4J_fabric_graph_1_uri=neo4j://core1:17687,neo4j://core2:27687,neo4j://core3:37687
      - NEO4J_fabric_graph_1_database=db2
      - NEO4J_fabric_graph_2_name=graphC
      - NEO4J_fabric_graph_2_uri=neo4j://core1:17687,neo4j://core2:27687,neo4j://core3:37687
      - NEO4J_fabric_graph_2_database=db3
      - NEO4J_dbms_connector_bolt_advertised__address=server2:57687
      - NEO4JLABS_PLUGINS=["apoc"]
